name = "palimian"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "palimian"
database_name = "palimian"
database_id = "58f3361e-1759-4571-986d-74602e34c281"